// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RideLedger.Infrastructure.Persistence;

#nullable disable

namespace RideLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260209063635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_accounts_tenant_id");

                    b.HasIndex("AccountId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_account_id_tenant_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BillingFrequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_frequency");

                    b.Property<DateTime>("BillingPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_period_end");

                    b.Property<DateTime>("BillingPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_period_start");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsImmutable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_immutable");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("outstanding_amount");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("paid_amount");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("subtotal_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_invoices_invoice_number");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_invoices_tenant_id");

                    b.HasIndex("AccountId", "BillingPeriodStart", "BillingPeriodEnd")
                        .HasDatabaseName("i_x_invoices_account_id_billing_period_start_billing_period_end");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.InvoiceLineItemEntity", b =>
                {
                    b.Property<Guid>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("line_item_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("service_date");

                    b.HasKey("LineItemId");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("i_x_invoice_line_items_invoice_id");

                    b.HasIndex("LedgerEntryId")
                        .HasDatabaseName("i_x_invoice_line_items_ledger_entry_id");

                    b.ToTable("invoice_line_items", (string)null);
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.LedgerEntryEntity", b =>
                {
                    b.Property<Guid>("LedgerEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("CreditAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("credit_amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<decimal?>("DebitAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("debit_amount");

                    b.Property<string>("LedgerAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ledger_account");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SourceReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_reference_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.HasKey("LedgerEntryId");

                    b.HasIndex("SourceReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_entries_payment_idempotency")
                        .HasFilter("source_type = 'Payment'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ledger_entries_tenant_id");

                    b.HasIndex("AccountId", "SourceReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_entries_ride_idempotency")
                        .HasFilter("source_type = 'Ride'");

                    b.HasIndex("AccountId", "TenantId")
                        .HasDatabaseName("ix_ledger_entries_balance_calc");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AccountId", "TenantId"), new[] { "DebitAmount", "CreditAmount" });

                    b.HasIndex("AccountId", "TransactionDate")
                        .HasDatabaseName("ix_ledger_entries_statements");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("MessageId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("i_x_outbox_messages_processed_at_occurred_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.HasOne("RideLedger.Infrastructure.Persistence.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_invoices_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.InvoiceLineItemEntity", b =>
                {
                    b.HasOne("RideLedger.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_invoice_line_items_invoices_invoice_id");

                    b.HasOne("RideLedger.Infrastructure.Persistence.Entities.LedgerEntryEntity", "LedgerEntry")
                        .WithMany()
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_invoice_line_items_ledger_entries_ledger_entry_id");

                    b.Navigation("Invoice");

                    b.Navigation("LedgerEntry");
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.LedgerEntryEntity", b =>
                {
                    b.HasOne("RideLedger.Infrastructure.Persistence.Entities.AccountEntity", "Account")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_ledger_entries_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.AccountEntity", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("RideLedger.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
